Repository 20sw084/3-Months-Preparation-Kit-HackerRank, pull requests merged in 2023-10, with the labels that each got.

#54 Leetcode 132 Pattern Added
  LeetCode Problems/Leetcode_132_Pattern.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#55 C++ solution for Reverse a link list
  Week7/Reverse-a-linked-list.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#59 code added for Misère Nim
  Week 6/Misère-Nim.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#79 Binary Tree PreOrder Traversal in Java
  LeetCode Problems/PreOrderTraversal.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#80 DivisibleSum Pair || HACKERRANK
  Week 1/DivisibleSumPair.java
  Week 1/problem2.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#81 Code added
  Week 6/integer-to-roman.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#82 Binary Tree PostOrder Traversal
  LeetCode Problems/PostOrderTraversal.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#83 Diagonal Difference || HackerRank
  Week 2/DiagnalDifference.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#86 Added Pow(x, n) in LeetCode Problems
  CONTRIBUTING.md
  LeetCode Problems/Pow(x, n)_50.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#88 Maximum subarray problem
  LeetCode Problems/SubArray.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#90 Basic Mathematical Programs || LeetCode
  LeetCode Problems/ArmstrongNo.java
  LeetCode Problems/PalindromicNo.java
  LeetCode Problems/Paythagorian Triplet.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#91 create Lonely Integer Pragram
  Week 2/LonelyInteger.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#92 Cycle Detection #Week 8 Problem
  Week8/DetectCycle.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#97 Insert node in a doubly Linked List
  Week8/insert_node.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#96 Balanced Brackets Problem (Week 8)
  Week8/BalancedBrackets.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#106 Create PalindromeChecker.java
  Week8/PalindromeChecker.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#107 Create MatrixMultiplication.java
  Week8/MatrixMultiplication.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#108 Create BinarySearch.java
  Week8/BinarySearch.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#109 Create Knapsack.java
  Week8/Knapsack.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#110 Used binary search algorithm
  LeetCode Problems/binarySearch.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#112 Create TreeSort.java
  Week8/TreeSort.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#113 Data Structure Linked List
  LeetCode Problems/linkedList.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#115 Week Three Problems
  CONTRIBUTING.md
  Week 3/DateDayRecognize.java
  Week 3/DistanceTravelled.java
  Week 3/EmailValidation.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#116 Find Max words.
  LeetCode Problems/maxwords.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#117 Pascal Triangle Solved
  CONTRIBUTING.md
  LeetCode Problems/Pascal_Triangle.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#118 leetcode
  LeetCode Problems/GoalParserIntrepretation_1678.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#119 Create MaximumNestingDepthOfTheParenthesis_1614.java
  LeetCode Problems/MaximumNestingDepthOfTheParenthesis_1614.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#120 Leetcode hard problem
  LeetCode Problems/MinimumBitFlipsToConvertNumber.java
  LeetCode Problems/N_Queens_51.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#121 oddeven
  LeetCode Problems/OddEvenLinkedList_328.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#124 Data structure and analysis
  dsa-nltp.ipynb
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#125 search_implementation.cpp
  search_implementation.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#127 week 7 updated
  Week7/Insert_a_node_at_a_specific_position_in_a_linked_list.cpp
  Week7/Sherlock_and_Anagrams.cpp
Labels: hacktoberfest, hacktoberfest-2023

#129 Create tan6.java
  StringReverse.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#130 CSV_file reads uisng python
  csv-file read dsa.ipynb
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#131 Add files via upload
  Week 4/GroceryShop.java
  Week 4/Palindrome.java
  Week 4/RSAEncryptionExample.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#132 Added python code to Merge two sorted list
  Merge_Two_sorted_list.py
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#134 Added RotationOfLinkedList.java file in LeetCode folder
  CONTRIBUTING.md
  LeetCode Problems/RotationOfLinkedList.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#136 LeetCode Problem 174 : Dungeon Game Solved
  LeetCode Problems/DungeonGame.py
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest-2023

#137 LinkedList
  Week 1/linkedList.java
  Week 2/ArrayStack.java
  Week 3/ApnaQueue.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#138 RPN Calculator DSA JAVA
  Week 4/RPN.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#139 ArrayLinkedList
  Week 5/LLArray.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#140 added peakIndexInAMountainArray
  LeetCode Problems/peakIndexInAMountainArray.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#141 Python basics
  python-basics.py
Labels: good first issue, hacktoberfest, hacktoberfest-2023

#142 Adding problems of week five
  Week 5/SAARCDemo.java
  Week 5/ShippingCharges.java
  Week 5/UpperAndLowerCase.java
  Week 5/ZigzagLoop.java
Labels: good first issue, hacktoberfest, hacktoberfest-2023
